name: Lint
on:
  push:
  pull_request:

jobs:
  autocorrect:
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@v3

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main
